### ISSUE TITLE
problem CH341A not connecting in windows

### ISSUE THREAD

**Issue by zaki1213-2** [bigbigmdm/IMSProg#105]
Will this be able to run on Windows?
I tried to run it in windows qt creator but CH341A is not connected, does it have its own ch341 driver?
currently i am using CH341a driver from AsProgrammer

**Comment by bigbigmdm** [comment]
The Linux kernel contains the [WinChipHead](https://www.wch-ic.com/) chip drivers. The Windows base system does not contain these drivers. I don't know any other driver for Windows except [CH341SER](https://www.wch-ic.com/products/CH341.html?).
