### ISSUE TITLE
Chips Database (IMSProg.Dat) not found after IMSProg startup

### ISSUE THREAD

**Issue by mega-ice** [bigbigmdm/IMSProg#14]
After compiling the source code and installing on Ubuntu 22.04, IMSProg cannot find the chip database file IMSProg.Dat.
I downloaded a new version using the IMSProg_database_update.sh script and put it in the /opt/IMSProg folder as described in the README.md file. The error persists.

I then used strace to look at what is being initialised and found that IMSProg is expecting the chip database file in the location /etc/imsprog/IMSProg.Dat. 

After copying the file there, the chip database is loaded correctly on startup.

fix:
```
sudo mkdir /etc/imsprog

sudo cp /opt/IMSProg/IMSProg.Dat /etc/imsprog
```

**Comment by bigbigmdm** [comment]
Thank you! In new branch use the /etc/imsprog folder. Tomorrow i will merge this branches and fix problems.
