### ISSUE TITLE
release/build/language incorrect qm

### ISSUE THREAD

**Issue by cappelikan** [bigbigmdm/IMSProg#15]
Please remove two files

https://github.com/bigbigmdm/IMSProg/blob/main/release/build/language/chipEditor_ua_UA.qm
https://github.com/bigbigmdm/IMSProg/blob/main/release/build/language/chipProgrammer_ua_UA.qm

Thanks.

**Comment by bigbigmdm** [comment]
Ok.

**Comment by cappelikan** [comment]
Please remove two files

https://github.com/bigbigmdm/IMSProg/blob/main/release/build/language/chipEditor_ua_UA.qm
https://github.com/bigbigmdm/IMSProg/blob/main/release/build/language/chipProgrammer_ua_UA.qm

The files have not been deleted, please delete them

Thanks.

**Comment by bigbigmdm** [comment]
Ok!
