### ISSUE TITLE
Editor launch from toolbar

### ISSUE THREAD

**Issue by blackPantherOS** [bigbigmdm/IMSProg#17]
To run the editor program from the main window of the programmer: It seems that you didn't apply[ the my patch to the editor's relative path in mainwindow.cpp](https://github.com/blackPantherOS/IMSProg/commit/0bf6b2795d010781334dbd84def8c870bdbad125), so the program can't be launched from the programmer's toolbar, only from the command line or a separated icon. The reason for this is that when the user launches itt, it is not in /usr/bin, but in its home directory, therefore the relative path will be invalid.

I am attaching two pictures to help you understand the problems...

**First showing the binary compiled from the current source code:** 
![wrong_path](https://github.com/bigbigmdm/IMSProg/assets/12883566/f896b8c5-c9ef-4c95-9d2a-7ab94e69124e)

**And this binary working fine after applying the my patch :**
![patched](https://github.com/bigbigmdm/IMSProg/assets/12883566/f370497a-fa6c-4f81-bee7-66b2a1b62f0c)

**Comment by bigbigmdm** [comment]
Can you please tell me if this is the main branch (1.1.2 tag)? I run this program normally...

**Comment by bigbigmdm** [comment]
Please show me that path again :)

**Comment by bigbigmdm** [comment]
I'm sorry! I found this Pull Request!

**Comment by bigbigmdm** [comment]
Please see the latest changes to the source code.

**Comment by bigbigmdm** [comment]
Thank you. I link to you in the debian/copyright.

**Comment by bigbigmdm** [comment]
Thank you. I link to you in the debian/copyright.
