### ISSUE TITLE
Запись со смещением.

### ISSUE THREAD

**Issue by DJs3000** [bigbigmdm/IMSProg#18]
Михаил, приветствую. А есть в интерфейсе возможность записи со смещением т.е. писать фал не с нуля, а скажем с 700000 адреса? Есть необходимость шить в одну микросхему 2 файла. Первый шьется с нуля, а второй со смещением.

**Comment by bigbigmdm** [comment]
Можно слить два бинарных файла в один, затем записать:
`cat file1.bin file2.bin > target_file.bin`

**Comment by DJs3000** [comment]
А точно, просто название у кнопки странное, но теперь буду пользоваться. Предварительно делать слияние далеко не всегда удобно, да и второй файлик не идёт сразу за первым. Да, можно в любом hex редакторе склеить, но это лишний гемор. Спасибо за подсказу.
