### ISSUE TITLE
Скорость записи.

### ISSUE THREAD

**Issue by DJs3000** [bigbigmdm/IMSProg#20]
Михаил, ещё раз приветствую. Заметил забавную особенность в плане разной скорости записи одной и той же флешки разным софтом. Шью флешку SPANSION S25FL064A на линуксе при помощи вашего IMSProg и на винде AsProgrammer https://github.com/nofeletru/UsbAsp-flash
Разница в скорости записи в 10 раз т.е. запись 5 мегабайтной прошивки в IMSProg проходит за ~20минут, а в AsProgrammer за ~2минуты. Нельзя ли как-то ускорить запись и в IMSProg?)

![photo_2023-11-22_07-07-56](https://github.com/bigbigmdm/IMSProg/assets/16526540/5ae56747-01f2-47ce-8bbd-e212ed829d62)

![222](https://github.com/bigbigmdm/IMSProg/assets/16526540/935dc3f8-6441-4f3d-8591-e08083fce27a)

**Comment by bigbigmdm** [comment]
Это странно. На [4PDA](https://4pda.to/forum/index.php?showtopic=1077823&st=20) мне сказали, что IMSProg быстрее, чем NEOProgrammer.  Про ASProgrammer не знаю. Winbond W25Q32BV (половинка от объема Вашей микросхемы) у меня считывается за 34сек, программируется за 5 мин 23 сек. В любом случае посмотрю, но не прямо сейчас. Сейчас первоочередная задача выложить IMSProg в репозиторий UBUNTU, а с этим пока засада. Потом займусь оптимизацией скорости. Дальше мечтаю перейти к CH347 - в консольной утилите этот программатор читает 25Q32 (4Mb) за 2 секунды.

**Comment by DJs3000** [comment]
Но могу зато IMSProg попадёт в репазиторий Эльбрус ОС, я его туда внесу.

**Comment by bigbigmdm** [comment]
Буду премного благодарен!

**Comment by DJs3000** [comment]
Видимо мне сбойная машина попалась. Вот сейчас прошивали биос с другой машины такую же флешку и со скоростью было высё хорошо.
