### ISSUE TITLE
Обновление базы поддерживаемых микросзем.

### ISSUE THREAD

**Issue by DJs3000** [bigbigmdm/IMSProg#21]
Михаил, приветствую. Немного душноты :) Если установить IMSprog, то в апликейшен попадает 3 файлика.
1. Программа IMSprog
2. Обновление базы поддерживаемых микросхем
3. Редактирование базы поддерживаемых микросхем
На мой дилетантский взгляд не совсем удобно получилось. По скрину видно, что 1 и 2 пункт названы одинаково, что создает путаницу. Может быть есть смысл обозвать 2 пункт как-то так: IMSprog base update? Если совсем начать умничать, то можно редактор и обновление поместить в основную программу или ссылки на эти программы были в основной меню IMSprog дабы не плодить 3 ярлыка. Возможно так будет удобнее.

![2023112417000280](https://github.com/bigbigmdm/IMSProg/assets/16526540/6b0a9af9-31b7-4e9e-b64c-f4efe33774e2)

**Comment by bigbigmdm** [comment]
Понял, поменяю desktop файл, возможно на IMSProg-updater - так покороче. Просто у меня две строки на каждый пункт, поэтому не обратил внимания. 
Не закрывайте пока, пожалуйста, а то я могу забыть...
![изображение](https://github.com/bigbigmdm/IMSProg/assets/75389103/aa2f25ea-a329-41c0-b89f-24622e1338d3)

**Comment by bigbigmdm** [comment]
Поменял на Name=IMSProg_updater - можно пересобрать.

**Comment by DJs3000** [comment]
Отлично! У тебя тут есть комментарий, а в xfce у меня не показывает этого.
