### ISSUE TITLE
Error on Verify function

### ISSUE THREAD

**Issue by VittorioBurani** [bigbigmdm/IMSProg#28]
`Verify` function on I2C EEPROMs fails when verifying files shorter than full EEPROM size because it searches for the dummy 0x00 used to pad the content by the `Program` function

Maybe adding some 0x00 padding also in the `Verify` function may solve the issue with hopefully low effort (in the virtual file content bytestring used to do the comparison you could pad accordingly to what happens during `Program`)

Issue find on Ubuntu 22.04 LTS, writing on the following IC:

- 24_EEPROM
- COMMON
- 24C256
- 32 K
- 32
- 3.3 V

**Comment by bigbigmdm** [comment]
Thanks, I'll look into it.

**Comment by bigbigmdm** [comment]
I fixed this error. Please test the new version.

**Comment by bigbigmdm** [comment]
I fixed this error. Please test the new version.

**Comment by mrv96** [comment]
Issue not 100% fixed: https://github.com/bigbigmdm/IMSProg/pull/29#issuecomment-1871286177
