### ISSUE TITLE
Help with settings for S93C56 BDDVAX 8913

### ISSUE THREAD

**Issue by luther7** [bigbigmdm/IMSProg#4]
I'm trying to read a chip marked S93C56 BDDVAX 8913. Any idea what settings I should use? Thanks!

**Comment by luther7** [comment]
Thanks! I think it may be my adapter.

![IMG_0819](https://github.com/bigbigmdm/IMSProg/assets/14562624/6aa0565c-2b14-447f-a5b0-5d9dab6dc078)
![IMG_0821](https://github.com/bigbigmdm/IMSProg/assets/14562624/274ac260-1e02-4755-a14b-b434749964e5)

**Comment by bigbigmdm** [comment]
I testing only 16bit mode.

**Comment by bigbigmdm** [comment]
Can you please tell me where I can buy such an adapter?

**Comment by luther7** [comment]
> Can you please tell me where I can buy such an adapter?

I purchased it from here: https://www.ebay.com.au/itm/195699712014

**Comment by luther7** [comment]
With a jumper across R4 in the converter, I think I can read it correctly using SNANDer.

**Comment by luther7** [comment]
Thanks for your help @bigbigmdm :heart:
