### ISSUE TITLE
README.md fix "What is this"

### ISSUE THREAD

**Issue by AndreiCherniaev** [bigbigmdm/IMSProg#55]
### Description

What is different between [EZP2019-EZP2025_chip_data_editor](https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor) and [IMSProg editor](https://github.com/bigbigmdm/IMSProg/tree/main/IMSProg_editor)?

I want to fix README.md text
"IMSProg - Linux IMSProg - I2C, MicroWire and SPI EEPROM/Flash chip programmer for CH341A devices. The IMSProg is a free programmer tool based on [QhexEdit2](https://github.com/Simsys/qhexedit2) and modified [SNANDer programmer](https://github.com/McMCCRU/SNANDer).

This is a GUI program used widget QhexEditor. For setting the SPI chip parameters you can use the Detect button for reading chip parameters (JEDEC information reading) or manually setting it. The I2C and MicroWire EEPROM only manually selected."
Looks like this repo contains two different programs: programmer and editor. If so then you should describe the programmer and describe the editor...

P.S. Please use English or Russian.

### Usage tips

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into this.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this.
* Subscribe to receive notifications on status change and new comments, you can do also without add comment.

**Comment by bigbigmdm** [comment]
1. What is different between [EZP2019-EZP2025_chip_data_editor](https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor) and [IMSProg editor](https://github.com/bigbigmdm/IMSProg/tree/main/IMSProg_editor)?
- only field names and folder search algorithm.
2. You're right. The editor should also be described, for example as (here)[https://antenna-dvb-t2.ru/IMSProg.php].

**Comment by AndreiCherniaev** [comment]
> 1. What is different between [EZP2019-EZP2025_chip_data_editor](https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor) and [IMSProg editor](https://github.com/bigbigmdm/IMSProg/tree/main/IMSProg_editor)?
> 
> 
>     * only field names and folder search algorithm.
> 
> 
>     2. You're right. The editor should also be described, for example as [here](https://antenna-dvb-t2.ru/IMSProg.php).

Я изучил ссылку. 
"Формат базы данных микросхем основан на формате программаторов EZP2019, EZP2020, EZP2023, Minpro I, XP866+. Для ее редактирования используется отдельный компонент программы."
Компонент программы - звучит очень непонятно.
Также вы говорите "Программа IMSProg". То есть в вашем мире есть программа IMSProg и она делится на два компонента: programmer, data base editor.

Я такого не встречал. Давайте рассмотрим какой-нибудь классический пример, да ещё и англоязычный. Если переводить на вашу разработку термины [из ](https://en.m.wikipedia.org/wiki/GNU_toolchain)
То получается что у вас есть 
collection of tools - набор утилит
1) Утилита programmer - programmer tool
2) Утилита data base editor - data base editor tool

Давайте примем такую терминологию?

**Comment by bigbigmdm** [comment]
3. Есть еще [скрипт](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg_database_update) обновления базы. 

Кое-что я писал в man по каждому из компонентов.
Давайте применим эту терминологию, но programmer - главная утилита, может жить самостоятельно, а остальные лишь делают работу с programmer более комфортной.

**Comment by AndreiCherniaev** [comment]
> 1. What is different between [EZP2019-EZP2025_chip_data_editor](https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor) and [IMSProg editor](https://github.com/bigbigmdm/IMSProg/tree/main/IMSProg_editor)?
> 
> 
>     * only field names and folder search algorithm.

So users shouldn't use EZP2019-EZP2025_chip_data_editor because it is deprecated. Users should use IMSProg instead. Correct?

**Comment by bigbigmdm** [comment]
@AndreiCherniaev EZP2019-EZP2025_chip_data_editor используется для других программаторов - (EZP2019 - EZP2025)[https://antenna-dvb-t2.ru/EZP_programmers.php]. У них только софт под Windows. Изначально я хотел написать программу под Linux для них, но у них закрытый код и его не заполучить. Мне понравился формат данных их базы микросхем и я использовал его в IMSProg, немного изменив "под себя" в процессе доработки программы.

**Comment by bigbigmdm** [comment]
@AndreiCherniaev , я добавил информацию в README. Вы посмОтрите?

**Comment by AndreiCherniaev** [comment]
> Кое-что я писал в man по каждому из компонентов. Давайте применим эту терминологию

Я вас не понимаю. Мы вчера кажется сошлись на том, что 
IMSProg is a collection of tools:
но вы пишите
"IMSProg consists of three executable modules:"
Поэтому я смущён...

**Comment by bigbigmdm** [comment]
Поправил.

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev EZP2019-EZP2025_chip_data_editor используется для других программаторов - [EZP2019 - EZP2025](https://antenna-dvb-t2.ru/EZP_programmers.php). У них только софт под Windows. Изначально я хотел написать программу под Linux для них, но у них закрытый код и его не заполучить. Мне понравился формат данных их базы микросхем и я использовал его в IMSProg, немного изменив "под себя" в процессе доработки программы.

![image](https://github.com/bigbigmdm/IMSProg/assets/27889022/57723d5e-3986-4565-aeaf-8b255f245a03)
Can you add link https://antenna-dvb-t2.ru/EZP_programmers.php in github's "Website" field?
P.S. Please use "Qt" not "QT".

**Comment by bigbigmdm** [comment]
В моем профиле есть [сайт](https://antenna-dvb-t2.ru), или Вы имеете ввиду в другом месте?

**Comment by AndreiCherniaev** [comment]
> В моем профиле есть [сайт](https://antenna-dvb-t2.ru), или Вы имеете ввиду в другом месте?

Я про вот это место, сюда добавить https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor
Can you add link https://antenna-dvb-t2.ru/EZP_programmers.php in github's "Website" field?
![image](https://github.com/bigbigmdm/IMSProg/assets/27889022/57723d5e-3986-4565-aeaf-8b255f245a03)
P.S. Please use "Qt" not "QT".

**Comment by bigbigmdm** [comment]
@AndreiCherniaev В первом приближении README готово. Можете посмотреть?

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev В первом приближении README готово. Можете посмотреть?

Ох у меня такая проблема что из-за незакрытого моего реквеста мои новые реквесты объединяются с незакрытым...
https://github.com/bigbigmdm/IMSProg/pull/57/commits/0542ae397e2019b71b6934a40cb8a63237755f6d

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev В первом приближении README готово. Можете посмотреть?

Сейчас думаю над этим текстом
**IMSProg** - Linux IMSProg - I2C, MicroWire and SPI EEPROM/Flash chip programmer for CH341A devices.

То есть IMSProg - Linux only? А почему так? Вроде Qt позволяет быть на всех платформах...

**Comment by bigbigmdm** [comment]
@AndreiCherniaev Так, вроде, все слилось как надо?

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev Так, вроде, все слилось как надо?

yes

**Comment by bigbigmdm** [comment]
@AndreiCherniaev "То есть IMSProg - Linux only? А почему так? Вроде Qt позволяет быть на всех платформах..." - под Windows это целая история с неподписанными драйверами на CH341A, под Linux они уже есть в ядре. Под MAC - не знаю...

**Comment by bigbigmdm** [comment]
@AndreiCherniaev , как закончите с README, дайте знать. Я сделаю новый таг и выпущу release

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev , как закончите с README, дайте знать. Я сделаю новый таг и выпущу release

У меня такая идея. Уже имеются разделы "Chip database editor" и "Chip updater". А почему нет раздела "chip programmer"? Похоже надо сделать раздел "chip programmer" и перенести туда текст

For setting the SPI chip parameters you can use the Detect button for reading chip parameters (JEDEC information reading) or manually setting it. The I2C and MicroWire EEPROM only manually selected.

The chip database format is clone with EZP2019, EZP2020, EZP2023, Minpro I, XP866+ programmers. You can edit the database use the EZP Chip data Editor

![CH341A EEPROM programmer](img/IMSProg_1.png)

![CH341A EEPROM programmer](img/IMSProg.png) 

А также всё что написано в разделе "## How to use:" до раздела "## Chip database editor"

Правилньо я думаю?

**Comment by AndreiCherniaev** [comment]
> По сути перед "How to use:" нужно добавить Chip_programmer или IMSProg_programmer.

Допустим перед "How to use:" добавлю "IMSProg_programmer". А вот этот текст разве не нужно перенести в этот новый раздел "IMSProg_programmer"?

For setting the SPI chip parameters you can use the `Detect` button for reading chip parameters (JEDEC information reading) or manually setting it. The I2C and MicroWire EEPROM only manually selected.

The chip database format is clone with EZP2019, EZP2020, EZP2023, Minpro I, XP866+ programmers. You can edit the database use the [EZP Chip data Editor](https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor)

И вот эти пикчи перенести в новый раздел?
![CH341A EEPROM programmer](img/IMSProg_1.png)

![CH341A EEPROM programmer](img/IMSProg.png)

**Comment by bigbigmdm** [comment]
Посмотрите, как сейчас: How to use --> chip programmer

**Comment by AndreiCherniaev** [comment]
> Посмотрите, как сейчас: How to use --> chip programmer

Я считаю что "How to use:" вообще лишний... Но это не принципиально... С [текстом-то](https://github.com/bigbigmdm/IMSProg/issues/55#issuecomment-1938682151) что делать?

**Comment by bigbigmdm** [comment]
"How to use:" я бы оставил для удобства навигации.

"For setting the SPI chip parameters you can use the Detect button for reading chip parameters (JEDEC information reading) or manually setting it. The I2C and MicroWire EEPROM only manually selected." - дубляж информации Chip type selecting - может совсем убрать?

"The chip database format is clone with EZP2019, EZP2020, EZP2023, Minpro I, XP866+ programmers. You can edit the database use the [EZP Chip data Editor](https://github.com/bigbigmdm/EZP2019-EZP2025_chip_data_editor)" - можно оставить
на старосм месте. По сути - информация по используемому формату.

**Comment by AndreiCherniaev** [comment]
> "For setting the SPI chip parameters you can use the Detect button for reading chip parameters (JEDEC information reading) or manually setting it. The I2C and MicroWire EEPROM only manually selected." - дубляж информации Chip type selecting - может совсем убрать?

Согласен, убирайте!

> можно оставить на старосм месте.
Согласен!

**Comment by bigbigmdm** [comment]
@AndreiCherniaev , мне кажется,это лишнее. Текст выше рассказывает об этом адаптере, на плате написано, что это такое.

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev , мне кажется,это лишнее. Текст выше рассказывает об этом адаптере, на плате написано, что это такое.

ok.

What about this images
`![CH341A black](img/ch341_black150.png)  ![CH341A green](img/ch341_green150.png) `
Может быть надо их подписать? К чему они вообще указаны?

**Comment by bigbigmdm** [comment]
@AndreiCherniaev мы доредактировались с Вами. Из  шапки пропало, что это программа для для программатора CH341A.

**Comment by bigbigmdm** [comment]
Это должно идти первым предложением.

**Comment by AndreiCherniaev** [comment]
> Это должно идти первым предложением.

**IMSProg** - **I**2C, **M**icroWire and **S**PI EEPROM/Flash chip **Prog**rammer - is a program to read, write EEPROM chips using programmers based on CH341A.

Good?

**Comment by bigbigmdm** [comment]
Good!

**Comment by bigbigmdm** [comment]
Я поднял картинку и опустил фразу о форматах. Теперь понятно, для чего она.

**Comment by AndreiCherniaev** [comment]
> Я поднял картинку и опустил фразу о форматах. Теперь понятно, для чего она.

Я могу только догадываться, что это
Example of programmers based on CH341A
Так?

**Comment by AndreiCherniaev** [comment]
А вот эти картинки - это про что? Не надо ли их перенеси в "Chip programmer"?
```
![CH341A EEPROM programmer](img/IMSProg_1.png)
![CH341A EEPROM programmer](img/IMSProg.png) 
```

**Comment by bigbigmdm** [comment]
Люди, которые этим занимаются знают эти картинки лучше нас с Вами. Это не существенно. И должны они быть сверху, чтобы сразу было видно о чем речь.

**Comment by bigbigmdm** [comment]
Поверьте, эту программу на Linux ждали около 10 лет

**Comment by AndreiCherniaev** [comment]
> Люди, которые этим занимаются знают эти картинки лучше нас с Вами. Это не существенно. И должны они быть сверху, чтобы сразу было видно о чем речь.

ok

**Comment by bigbigmdm** [comment]
@AndreiCherniaev мне кажется, что у нас с Вами хорошо получилось. Еще бы man файлы посмотреть...

**Comment by AndreiCherniaev** [comment]
> man файлы

Give link please...

**Comment by bigbigmdm** [comment]
[1](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg.1.gz)
[2](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_editor/other/IMSProg_editor.1.gz)
[3](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg_database_update.1.gz)

**Comment by AndreiCherniaev** [comment]
> [1](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg.1.gz) [2](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_editor/other/IMSProg_editor.1.gz) [3](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg_database_update.1.gz)

How I can make commit here?

**Comment by bigbigmdm** [comment]
Download -> unzip -> edit ->zip->upload

**Comment by AndreiCherniaev** [comment]
> Download -> unzip -> edit ->zip->upload It is a standard man document.

И как вы будете мои изменения отсматривать? Разжимать у себя обратно и сравнивать? How another software host man files? I believe should be better solution...

**Comment by bigbigmdm** [comment]
Это одноразовая акция, так что да. Эти файлы, я надеюсь, меняться не будут.

**Comment by AndreiCherniaev** [comment]
> Это одноразовая акция, так что да. Эти файлы, я надеюсь, меняться не будут.

Сначала я увижу 2 недостатка и поправлю. Через час ещё два. Завтра ещё. И каждый раз unzip-zip. Очень грустно. Надо бы узнать как другие проекты это автоматизируют и тоже автоматизировать?

**Comment by bigbigmdm** [comment]
Это номинальные файлы, дающие краткую информацию и отсылающие к index.html. Чисто теоретически можно их жать с помощью [cmake](https://stackoverflow.com/questions/7050997/zip-files-using-cmake).

**Comment by bigbigmdm** [comment]
@AndreiCherniaev просто lintian сообщил в предупреждениях о необходимости man инструкций, которые для GUI программы мало интересны, но традиция... Вот генерация Index.html меня сейчас занимает больше. Поскольку он создан на основе README.md и чтобы не тащить за собой три десятка картинок я вставил их внутрь документа в base64. Fantu нашел инструмент, который хорошо конвертирует [readme в html](https://github.com/bigbigmdm/IMSProg/issues/50), но изображения в bsd64 он не переводит.

**Comment by bigbigmdm** [comment]
@AndreiCherniaev их нельзя исключать. Они копируются в систему при установке. Давайте пока оставим их в покое.
