### ISSUE TITLE
uk translate

### ISSUE THREAD

**Issue by cappelikan** [bigbigmdm/IMSProg#6]
[uk.zip](https://github.com/bigbigmdm/IMSProg/files/13049444/uk.zip)

**Comment by bigbigmdm** [comment]
Thank you for a job well done!

**Comment by cappelikan** [comment]
> Thank you for a job well done!
When I was making translations, I forgot that I had indicated the wrong encoding in the file name ua_UA there is no such encoding but there is uk_UA, please delete the files

chipEditor_ua_UA.qm

chipProgrammer_ua_UA.qm

they should stay instead

chipEditor_uk_UA.qm

chipEditor_uk_UA.ts

chipProgrammer_uk_UA.qm

chipProgrammer_uk_UA.ts

**Comment by bigbigmdm** [comment]
Ok!

**Comment by cappelikan** [comment]
Thanks
