### ISSUE TITLE
Uninstall script missing?

### ISSUE THREAD

**Issue by ziltoid-linux** [bigbigmdm/IMSProg#64]
Hello, newbie here.

How should I uninstall the program? I didn't find any script so I tried with `sudo make uninstall` but I received the error message `make: *** No rule to make target 'uninstall'.  Stop.`.

To install the program I unpacked the tar.gz and run `build_all.sh`.

**Comment by bigbigmdm** [comment]
I didn't write the deletion script.
Please see the [project structure](https://github.com/bigbigmdm/IMSProg#project-structure) and remove all files:
sudo rm -rf /usr/bin/IMSProg
sudo rm -rf /usr/bin/IMSProg_editor
sudo rm -rf /usr/bin/IMSProg_database_update 
sudo rm -rf /usr/share/imsprog
sudo rm -rf /usr/share/applications/IMSProg.desktop
sudo rm -rf /usr/share/applications/IMSProg_editor.desktop
sudo rm -rf /usr/share/applications/IMSProg_database_update.desktop
sudo rm -rf /usr/share/man/man1/IMSProg_editor.1.gz  
sudo rm -rf /usr/share/man/man1/IMSProg.1.gz
sudo rm -rf /usr/share/man/man1/IMSProg_database_update.1.gz
sudo rm -rf /usr/share/pixmaps/IMSProg64.png
sudo rm -rf /usr/share/pixmaps/IMSProg_database_update.png 
sudo rm -rf /usr/share/pixmaps/chipEdit64.png

**Comment by Fantu** [comment]
CMake don't provide uninstall but can be added, I did a basic one for example for another project (based on other): https://github.com/veeam/blksnap/commit/f4b6f0c7a33dcdba287448d979ce6caa4adebe82 (see CMakeLists.txt and cmake/cmake_uninstall.cmake.in)
About install for users I recommend using packages if possible.

**Comment by ziltoid-linux** [comment]
I understand, thank you for the fast reply.
