### ISSUE TITLE
brocken comments in udev rule 99-CH341.rules

### ISSUE THREAD

**Issue by antohami** [bigbigmdm/IMSProg#65]
### Distribution

ALT Linux

### Architecture

any

### Kernel version

any

### IMSProg version

1.3.2

### Bug description

Error due to incorrect formatting of comments.

### Steps to reproduce

$ /sbin/udevadm -V
254
$ /sbin/udevadm verify 99-CH341.rules
/home/data/gear/IMSProg/IMSProg_programmer/other/99-CH341.rules:1 Invalid key/value pair, ignoring.
/home/data/gear/IMSProg/IMSProg_programmer/other/99-CH341.rules:2 Invalid key/value pair, ignoring.
/home/data/gear/IMSProg/IMSProg_programmer/other/99-CH341.rules: udev rules check failed.

1 udev rules files have been checked.
  Success: 0
  Fail:    1

### Expected behavior

$ /sbin/udevadm verify 99-CH341.rules 

1 udev rules files have been checked.
  Success: 1
  Fail:    0

### Additional information

Must use # at the beginning of the line.

**Comment by bigbigmdm** [comment]
@antohami , thank you! Fixed.
