### ISSUE TITLE
Feature: recent files

### ISSUE THREAD

**Issue by carbofos** [bigbigmdm/IMSProg#7]
Thank you for a good software but the feature is realy missing is recently open files.
Also it does not  remember last opened directory. All the path should be passed again and again from the start to open a firmware.

**Comment by bigbigmdm** [comment]
Thanks for the good review of IMSProg. I will think about the functions to memorise file paths.

**Comment by bigbigmdm** [comment]
Your wish has come true!
Ver. 1.0.28 - Bad display of qComboBoxes in UBUNTU, Manjaro linux fixed, display of monospaced font in Manjaro linux fixed. Changed the default file path to the home directory. The last file path is saved and new file operations are processed using the last path.

**Comment by carbofos** [comment]
Thank you.
I did check out the last version and it's more beatuful.
But if I close the program and run it again it does not remember the last directory again.
It is not a big problem but it's annoying when the path is very long.

**Comment by bigbigmdm** [comment]
When I read your comment, I thought that this function is exactly as I made it. I did not plan to create an .ini file and store the last path in that file.

**Comment by carbofos** [comment]
I do not know why you do not want to save current settings in .ini file but it's exactly the same way like all popular software works. You can check out the behaviour. E.g. vscode, LibreOffice, NeoProgrammer e.t.c.

**Comment by bigbigmdm** [comment]
You can add a symbol link to the EEPROM directory that will be displayed when you open the file in the IMSProg program.
`ln -s /home/<...your folder path...> MY_EEPROM`.
![fold](https://github.com/bigbigmdm/IMSProg/assets/75389103/fe932121-8a32-44e0-80cc-a6fb4aa7ea46)



 I will probably add the ini file to IMSProg. But that's not the first priority. Right now I need help in creating a DEB package with source code to be hosted on UBUNTU Launchpan.net.
