### ISSUE TITLE
Change github About

### ISSUE THREAD

**Issue by AndreiCherniaev** [bigbigmdm/IMSProg#72]
### Description

I suggest new About text from [here](https://github.com/AndreiCherniaev/IMSProg_fix)

I make tags using [Wikipedia](https://en.wikipedia.org/wiki/Programmer_(hardware))...

### Usage tips

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into this.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this.
* Subscribe to receive notifications on status change and new comments, you can do also without add comment.

**Comment by AndreiCherniaev** [comment]
I am talking about this

![IMSProg about](https://github.com/bigbigmdm/IMSProg/assets/27889022/57bd205f-44da-4521-a208-09fb80849935)

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev Oooh, now I get it! Thanks!

I also suggest you to add tags:
chip-programmer 
prom-writer
! Like on my example...

**Comment by bigbigmdm** [comment]
@AndreiCherniaev , I have once again supplemented the `readme.md` file. Please have a look at it.

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev , I have once again supplemented the `readme.md` file. Please have a look at it.

Thank you. Looks ok.

**Comment by AndreiCherniaev** [comment]
@bigbigmdm  let's add new tags to github about?
CH347T
engineering
hacking
hardware
reverse

@taotieren do you have ideas to add/remove some tags on the github? I think we should have the same tags on the github and on the AUR [pack1](https://aur.archlinux.org/packages/imsprog-git) and [pack2](https://aur.archlinux.org/packages/imsprog)...

**Comment by taotieren** [comment]
> [@bigbigmdm](https://github.com/bigbigmdm) let's add new tags to github about? CH347T engineering hacking hardware reverse
> 
> [@taotieren](https://github.com/taotieren) do you have ideas to add/remove some tags on the github? I think we should have the same tags on the github and on the AUR [pack1](https://aur.archlinux.org/packages/imsprog-git) and [pack2](https://aur.archlinux.org/packages/imsprog)...

Right, I’ve added a new tag to the package on AUR: https://aur.archlinux.org/packages/imsprog-git

**Comment by bigbigmdm** [comment]
@AndreiCherniaev , please hold on a moment. I'm having a problem with the Debian packages: [Bug#1138885: RFS: imsprog/1.8.5-1 -- Linux chip programmer for CH341A/CH347T devices](https://lists.debian.org/debian-mentors/2026/06/msg00096.html). I need to change the debian/latest branch.
