### ISSUE TITLE
Translation part in readme

### ISSUE THREAD

**Issue by Fantu** [bigbigmdm/IMSProg#79]
### Description

I think is useful to add a translation part in readme, small example below taking from older commit and adding a small note for contributing to add new language (to be improved):

## Translations

Hungarian translation by [blackPantherOS](https://github.com/blackPantherOS),
Italian translation by Marino Pasquale and [Giovanni Scafora](https://github.com/giovanni69),
Brasil translation by Alexandre C. Leite,
Ukrainian translation by Sergey Golovko

Anyone can add or improve a translation by making a [pull request](https://github.com/bigbigmdm/IMSProg/pulls).
Translations files are located in: [IMSProg_programmer/language/](https://github.com/bigbigmdm/IMSProg/tree/main/IMSProg_programmer/language) and [IMSProg_editor/language/](https://github.com/bigbigmdm/IMSProg/tree/main/IMSProg_editor/language)

### Usage tips

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into this.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this.
* Subscribe to receive notifications on status change and new comments, you can do also without add comment.

**Comment by bigbigmdm** [comment]
@Fantu, put this part after `Licensing`?

**Comment by Fantu** [comment]
Yes can be put after Licensing and also add it in the menu on header

about `debian/copyright` adding new italian translator should be done after import of new upstream version including it
