### ISSUE TITLE
uk translate desktop files 

### ISSUE THREAD

**Issue by cappelikan** [bigbigmdm/IMSProg#8]
IMSProg_editor.desktop

Comment[uk]=Редактор бази мікросхем для IMSProg
GenericName[uk]=Редактор бази мікросхем для IMSProg

IMSProg.desktop

Comment[uk]=Программатор i2c,SPI,MW мікросхема для CH341a
GenericName[uk]=Программатор i2c,SPI,MW мікросхема для CH341a

IMSProg_database_update.desktop

Comment[uk]=Оновлення бази даних мікросхеми для IMSProg
GenericName[uk]=Оновлення бази даних мікросхеми для IMSProg

**Comment by bigbigmdm** [comment]
Ok!
