### ISSUE TITLE
Getting read/write failure 

### ISSUE THREAD

**Issue by UpDownSide** [bigbigmdm/IMSProg#82]
### Distribution

Raspbian GNU/Linux 11 (bullseye)

### Architecture

armhf

### Kernel version

6.1.21-v7+ #1642

### IMSProg version

1.3.7

### Bug description

Can't read block 0 or write block 0

**Comment by Fantu** [comment]
I suppose you have issue with udev rule, I saw some topic about with raspbian time ago, even if I had not thorough.
Another possibility if you use it with remove access (so don't take permission for uaccess tag) and your user is not in the plugdev group. Can you tell if is your case?

**Comment by bigbigmdm** [comment]
If the programmer was detected normally (status CH341A: `connected` in the status bar of the main screen), refer to the readme.MD file to learn about SFDP and the status register:
"If the SPI NOR FLASH chip is detected normally but is not read (gives the message Error reading sector 0), then in the Chip info window you can change bits BP4 and BP3 to zero and press the Write registers button. Then repeat the chip reading operation." 

Please see the screenshots.

**Comment by UpDownSide** [comment]
> If the programmer was detected normally (status CH341A: `connected` in the status bar of the main screen), refer to the readme.MD file to learn about SFDP and the status register: "If the SPI NOR FLASH chip is detected normally but is not read (gives the message Error reading sector 0), then in the Chip info window you can change bits BP4 and BP3 to zero and press the Write registers button. Then repeat the chip reading operation."
> 
> Please see the screenshots.

I've tried it! It doesn't write, but i'm able to erase it! The device is connected, the chip is where it needs to be. When trying to write same message!

**Comment by bigbigmdm** [comment]
@UpDownSide , Please set all bits of status register 0 to zero

**Comment by bigbigmdm** [comment]
Please setting to zero all bits in Status register 0

One more question:
Do you connect the chip to the programmer directly or with an alligator clip?

Please send me a screenshot of the SFDP form (chip information).

**Comment by UpDownSide** [comment]
> Please setting to zero all bits in Status register 0
> 
> One more question: Do you connect the chip to the programmer directly or with an alligator clip?
> 
> Please send me a screenshot of the SFDP form (chip information).

![2024-05-01-151322_1920x1080_scrot](https://github.com/bigbigmdm/IMSProg/assets/47486602/6d60f990-e1db-4cec-953b-8dd62274f345)
`root@raspberrypi:/etc/udev/rules.d# lsusb
Bus 001 Device 005: ID 0e8f:00a8 GreenAsia Inc. 2.4G RX
Bus 001 Device 006: ID 1a86:5512 QinHeng Electronics CH341 in EPP/MEM/I2C mode, EPP/I2C adapter
Bus 001 Device 003: ID 0424:ec00 Microchip Technology, Inc. (formerly SMSC) SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Microchip Technology, Inc. (formerly SMSC) SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`
output snap from: nano 99-com.rules
`SUBSYSTEM=="input", GROUP="input", MODE="0660"
SUBSYSTEM=="i2c-dev", GROUP="i2c", MODE="0660"
SUBSYSTEM=="spidev", GROUP="spi", MODE="0660"
SUBSYSTEM=="bcm2835-gpiomem", GROUP="gpio", MODE="0660"
SUBSYSTEM=="rpivid-*", GROUP="video", MODE="0660"

KERNEL=="vcsm-cma", GROUP="video", MODE="0660"
SUBSYSTEM=="dma_heap", GROUP="video", MODE="0660"
`

**Comment by bigbigmdm** [comment]
@UpDownSide , thank's for the screenshot.

One more question:
Do you connect the chip to the programmer directly or with an alligator clip?

**Comment by UpDownSide** [comment]
#

> @UpDownSide , thank's for the screenshot.
> 
> One more question: Do you connect the chip to the programmer directly or with an alligator clip?

No... that chip is inserted on the reader!

**Comment by bigbigmdm** [comment]
This is very strange! I tested IMSProg also with W25Q256FV and the result was fine. Maybe the chip was damaged? You can test windows programs: neoprogrammer, ch341a programmer, SiberiaProg (you can download them from https://ch341a.com/). I want to understand what the problem is.

**Comment by UpDownSide** [comment]
there's no need to add a rule on 99-com.rules file? i've seem something like this on github 'SUBSYSTEM=="usb", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="5512", MODE:="0666"'

**Comment by UpDownSide** [comment]
> This is very strange! I tested IMSProg also with W25Q256FV and the result was fine. Maybe the chip was damaged? You can test windows programs: neoprogrammer, ch341a programmer, SiberiaProg (you can download them from https://ch341a.com/). I want to understand what the problem is.

i've tried it already... didn't get result

**Comment by bigbigmdm** [comment]
Yes it is correct rule, but if he not working the progarmmer not detected in the IMSProg. You can also running the IMSProg from the sudo.

"i've tried it already... didn't get result" - If there was no result - the chip is damaged.
