### ISSUE TITLE
Not found file `IMSProg_editor` (dep pkg)

### ISSUE THREAD

**Issue by Podolyakofs** [bigbigmdm/IMSProg#9]
Good day, 
after installing deb package (v1.0.29-3/Ubuntu 22.04)  can't open "Edit chip database" (ctrl+q) with "Not found file `IMSProg_editor` error" and same error on program start

![image](https://github.com/bigbigmdm/IMSProg/assets/3431942/cc4615b3-5915-4a97-8f2b-fd57689e86ae)

Separately IMSProg_editor can be opened
![image](https://github.com/bigbigmdm/IMSProg/assets/3431942/eca94ded-9362-4fdd-94c0-b96ded94db1c)

**Comment by bigbigmdm** [comment]
Package version 1.0.29-3 does not exist. Please install version 1.0.29-2 and test it. The /opt/IMSProg folder should contain the following files: IMSProg, IMSProg.Dat, IMSProg_editor.

**Comment by Podolyakofs** [comment]
Thanks, downgraded package - now everything works

**Comment by bigbigmdm** [comment]
Can you please tell me if this is the main branch? I run this program normally...
