### ISSUE TITLE
The `TAG+="uaccess"` has no effect in the udev rule

### ISSUE THREAD

**Issue by wucke13** [bigbigmdm/IMSProg#98]
As hinted [here](https://github.com/systemd/systemd/issues/4288#issuecomment-348166161), udev `uaccess` is granted by  `/usr/lib/udev/rules.d/73-seat-late.rules`. So having a rule add the `uaccess` tag after `73-seat-late.rules` ran has not effect. The rules are ran in lexical order, so to be compatible with the `uacccess` system, the rule must be renamed, i.e. to `70-CH341.rules`.

https://github.com/bigbigmdm/IMSProg/blob/062b2f0488d2e8fc4adbabaffbff6fb958ad26f2/IMSProg_programmer/other/99-CH341.rules#L3-L3

**Comment by bigbigmdm** [comment]
@wucke13 , `GROUP=‘plugdev’` is not enough for the current user to get permissions?

**Comment by bigbigmdm** [comment]
@Fantu , may I have your opinion on this? ([Pull request](https://github.com/bigbigmdm/IMSProg/pull/99))

**Comment by wucke13** [comment]
Fixed by 947320fca4878b46beefbee05e47279c3b27f94e
